# Generated by Django 5.2.5 on 2025-08-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
            ],
            options={
                'unique_together': {('activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ValorPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('weight', models.DecimalField(decimal_places=6, max_digits=10)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo', 'fecha')},
            },
        ),
    ]
