# Generated by Django 5.2.5 on 2025-08-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=6)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.portafolio')),
            ],
        ),
    ]
